### ISSUE TITLE
Not working with 1803

### ISSUE THREAD

**Issue by purevertigo** [benchdoos/WeblocOpener#4]
When I double click the file. Nothing happens.

**Comment by benchdoos** [comment]
Can you send filename of the opening file?

**Comment by purevertigo** [comment]
Hi!

It is pretty much any shortcut I click. I double-click and then nothing...

**Comment by benchdoos** [comment]
Okay, can you archive with log files to weblocopener@gmail.com?
You can find them at:
C:\Users\<username>\AppData\Local\Temp\WeblocOpener\Log\
Zip them with any archiver you have and send in attouchments to my mail, I'll try to help you

**Comment by purevertigo** [comment]
This is still not working with current windows.
