### ISSUE TITLE
Privacy statement

### ISSUE THREAD

**Issue by gitguys** [benchdoos/WeblocOpener#5]
Can't find a privacy statement anywhere on your website or here.  Do you gather any information from the application and, if so, what exact information do you gather and who do you share it with?

Thanks.

**Comment by benchdoos** [comment]
Hello! Application gather information about your pc hardware and files you’re opening. That information stores locally on your pc as in log files (see: C:\Users\<username>\AppData\Local\Temp\WeblocOpener\Log\). 
This information is never send to me or any 3rd person. Log files stored only on your pc.
Log files are used to detect mistakes in application, if something work wrong. 
**I reach log files only if user decide to send by himself by email.**
