### ISSUE TITLE
Failure to detect newer Java versions on install

### ISSUE THREAD

**Issue by yetisyny** [benchdoos/WeblocOpener#57]
The installer specifically requires Eclipse Temurin from Adoptium version 17. However there are newer versions such as Java 21, the current LTS release of Java that is the default download version of Eclipse Temurin at the Adoptium website. These newer versions are backwards compatible with WeblocOpener 2.0.0 and 2.0.1. However, the installers for WeblocOpener 2.0.0 and 2.0.1 specifically require you to have Eclipse Temurin from Adoptium version 17, rather than the newer Eclipse Temurin from Adoptium version 21.

It is not really convenient to have multiple versions of Java on the same computer. This program WeblocOpener ought to be able to detect if the user has Eclipse Temurin from Adoptium version 17 or a newer version such as 18, 19, 20, or 21, and work fine on any of those, in the installer, and allow the installation to continue, rather than forcing the user to specifically use version 17, which is not the latest version. Version 21 is currently the LTS version of Java and there do not seem to be any compatibility issues for WeblocOpener, other than with the installer not recognizing it. It runs perfectly fine if it has already been installed.

So the installer should be updated to accept newer versions of Eclipse Temurin from Adoptium. That way it can be compatible with other software people use that uses even newer versions of Java than Java 17. I understand it has a minimum requirement of Java 17, but setting the maximum requirement to also be Java 17 makes things inconvenient for users, especially ones who just go to the Adoptium website and install the default Temurin which is version 21 LTS now. This would work fine if the installer just recognized it and approved of it as OK.

The main reason this is a problem is if you go to the Adoptium website when instructed by the installer, you specifically have to choose the older LTS version 17 rather than the current LTS version 21 in order to satisfy the WeblocOpener installer, which is not the default option on the Adoptium website. This can inconvenience and confuse users (like me, it definitely inconvenienced me, but probably other people too).

Oh and to clarify this is only an issue with the WeblocOpener installer refusing to install unless you specifically have version 17 of Eclipse Temurin from Adoptium installed. The WeblocOpener program itself, once you already have it installed, works perfectly fine with newer versions of Eclipse Temurin without any issues at all, only the installer has this issue with refusing to accept newer Java versions.

Thanks.

**Comment by benchdoos** [comment]
Hello, thank you for your feedback!
The installer will be fixed next release after full capability check.

**Comment by benchdoos** [comment]
@yetisyny Hello! WeblocOpener v2.0.2 must fix the problem, installing the update may proceed correctly.
